-- Create the table
create table public.reading_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  wpm int not null,
  words_read int not null,
  duration_seconds int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.reading_sessions enable row level security;

-- Create Policy
create policy "Users can insert their own sessions"
  on public.reading_sessions for insert
  with check (auth.uid() = user_id);

create policy "Users can view their own sessions"
  on public.reading_sessions for select
  using (auth.uid() = user_id);
