import '../../domain/entities/reading_session.dart';

class ReadingSessionModel extends ReadingSession {
  const ReadingSessionModel({
    super.id,
    required super.userId,
    required super.wpm,
    required super.wordsRead,
    required super.durationSeconds,
    required super.createdAt,
  });

  factory ReadingSessionModel.fromJson(Map<String, dynamic> json) {
    return ReadingSessionModel(
      id: json['id'] as int?,
      userId: json['user_id'] as String,
      wpm: json['wpm'] as int,
      wordsRead: json['words_read'] as int,
      durationSeconds: json['duration_seconds'] as int,
      createdAt: DateTime.parse(json['created_at'] as String).toLocal(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // ID is generated by DB
      'user_id': userId,
      'wpm': wpm,
      'words_read': wordsRead,
      'duration_seconds': durationSeconds,
      // 'created_at': is generated by DB usually, or we send it
      'created_at': createdAt.toIso8601String(),
    };
  }
}
